version: 2

sources:
  - name: silver
    schema: silver
    freshness:
      warn_after: {count: 30, period: minute}
      error_after: {count: 2, period: hour}
    loaded_at_field: updated_at
    tables:
      - name: reviews_current
      - name: reviews_enriched
